# 
name: "hello world"

on:
  push:
    branches:
      - master

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: hello "hello world"
        run: echo "hello world"

      - name: antoher job
        run: Write-output "Hellow world from PWSH"
        shell: pwsh
