name: CI

on:
  push:
    branches:
    - meetup_action_test

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: .\MyScripts\meetup.ps1
